# Generated by Django 6.0.4 on 2026-04-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('gis', 'GIS & Esri Technologies'), ('web', 'Web & App Development'), ('cloud', 'Cloud & Infrastructure'), ('pylib', 'Python GIS/ML Libraries'), ('raster', 'Raster, Image & Remote Sensing'), ('tools', 'Tools')], max_length=20),
        ),
    ]
