# Generated by Django 6.0.4 on 2026-05-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('venue', models.CharField(help_text='e.g. ISPRS Conference 2024', max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year', 'title'],
            },
        ),
    ]
