# Generated by Django 6.0.4 on 2026-05-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='static_image',
            field=models.CharField(blank=True, help_text='Path relative to static root, e.g. files/project_1.png', max_length=200),
        ),
    ]
